# Set update schedule for GitHub Actions and the Docker base image

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      # Check for updates to the base image every week
      interval: "weekly"
